name: Secret Scan with Gitleaks

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install gitleaks
        run: |
          curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64 -o gitleaks
          chmod +x gitleaks

      - name: Run gitleaks and generate JSON + TXT reports
        id: gitleaks_scan
        run: |
          # Lancement du scan sur tout le repo
          # On capture le code de retour sans casser le pipeline
          set +e
          ./gitleaks detect \
            --source . \
            --report-format json \
            --report-path gitleaks-report.json
          EXIT_CODE=$?
          set -e

          # Génération d'un rapport TXT lisible à partir du JSON
          # Si jq n'est pas dispo, on l'installe
          if ! command -v jq >/dev/null 2>&1; then
            sudo apt-get update -y
            sudo apt-get install -y jq
          fi

          if [ -f gitleaks-report.json ]; then
            # Conversion simplifiée du JSON vers TXT
            echo "=== Gitleaks Scan Report (human readable) ===" > gitleaks-report.txt
            jq -r '
              if (type == "array") then
                .[] | "Rule: \(.rule_id // "N/A")\nDescription: \(.description // "N/A")\nFile: \(.file // "N/A")\nStart Line: \(.start_line // "N/A")\nEnd Line: \(.end_line // "N/A")\nSecret: \(.secret // "REDACTED")\n---"
              else
                . # Cas où le format serait différent
              end
            ' gitleaks-report.json >> gitleaks-report.txt || echo "Impossible de parser le JSON, voir gitleaks-report.json brut." >> gitleaks-report.txt
          else
            echo "Aucun fichier gitleaks-report.json généré" > gitleaks-report.txt
          fi

          # Affichage d'un message lisible dans les logs
          if [ "$EXIT_CODE" -eq 0 ]; then
            echo "No Vulnerability detected"
          else
            echo "Vulnerability detected"
          fi

          # On stocke le code retour pour usage éventuel, mais
          # on FORCE le succès du job pour que le pipeline soit toujours vert
          echo "exit_code=$EXIT_CODE" >> $GITHUB_OUTPUT
          exit 0

      - name: Upload JSON report
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-json-report
          path: gitleaks-report.json
          if-no-files-found: warn

      - name: Upload TXT report
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-txt-report
          path: gitleaks-report.txt
          if-no-files-found: warn
