# test_secret.py

# GitHub token (pattern reconnu)
GITHUB_TOKEN = "ghp_1234567890ABCDEFGHIJKLMNOPQRST"

# AWS keys
AWS_ACCESS_KEY_ID = "AKIA1234567890FAKEKEYEXAMPLE"
AWS_SECRET_ACCESS_KEY = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
